import { BigText } from "../_components/projects/bigText"
import { Hero } from "../_components/projects/hero"
import { NextProject } from "../_components/projects/nextProject"
import { aiStorybookMeta } from "../projectMeta"

export default function Page() {
  return (
    <div>
      <Hero projectMeta={aiStorybookMeta} />
      <BigText skills={[...aiStorybookMeta.tech, "html", "css"]}>
        The project calls APIs from Replicate to use various AI model on
        language and image to generate stories and visuals. Similar to
        choose-your-own-adventure style games, you can define the next sequence
        in the story by typing in your own words or choosing the options
        generated by AI. Then, following your input, the AI will generate the
        next paragraph as well as an image that best depicts the current scene.
        Then, you will take the next turn, and so forth.<br></br>
        <br></br>
        This project is written in plain Typescript.
      </BigText>
      <NextProject currentProject={aiStorybookMeta} />
    </div>
  )
}
